blueprint:
  name: Alarm Alerts
  description: Critical push notifications when an alarm goes off.
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/alarm_alerts.yaml
  input:
    area:
      name: Area
      description: What is the name of the area for the alert?
      selector:
        text:
    alarm_sensors:
      name: Alarm Sensors
      description: Which sensors should be monitored?
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    delay:
      name: Repeat Delay
      description: How long to wait before repeating the alert?
      default: { minutes: 2 }
      selector:
        duration:

mode: single
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input alarm_sensors
  to: 'on'

variables:
  area: !input area

action:
- repeat:
    while:
    - condition: state
      entity_id: !input alarm_sensors
      match: any
      state: 'on'
    sequence:
    - service: notify.notify
      data:
        data: { push: { sound: { name: 'Default', critical: true, volume: true } } }
        title: ALARM!
        message: '{{ area }} alarm has been triggered!'
    - delay: !input delay
