blueprint:
  name: HomeSeer WX-300 Covers
  description: Control covers with paddle taps on a HomeSeer WX-300 switch.
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/homeseer_wx300_covers.yaml
  input:
    covers:
      name: Covers
      description: Which covers to control with the switch paddles?
      selector:
        entity:
          domain: cover
          multiple: true
    switch:
      name: Switch
      description: Which switch to use?
      selector:
        device:
          filter:
          - { manufacturer: HomeSeer Technologies, model: HS-WX300 }
          - { manufacturer: HomeSeer Technologies, model: HS-WD200+ }
          - { manufacturer: HomeSeer Technologies, model: HS-WS200+ }
    paddle_taps:
      name: Paddle Taps
      description: How many taps on a paddle are required?
      default: 'KeyPressed'
      selector:
        select:
          mode: dropdown
          options:
          - label: 'Single'
            value: 'KeyPressed'
          - label: 'Double'
            value: 'KeyPressed2x'
          - label: 'Triple'
            value: 'KeyPressed3x'
          - label: 'Quadruple'
            value: 'KeyPressed4x'
          - label: 'Quintuple'
            value: 'KeyPressed5x'
    paddle_hold:
      name: Paddle Hold
      description: Open and close the covers when holding down a paddle?
      default: false
      selector:
        boolean:
    state_variable:
      name: State Variable
      description: |
        This automation requires a Number helper to store the current state of the shade.
        Please create one that goes from 0 to 4 and select it here.
        Must only be shared with automations controlling the same set of shades.
      selector:
        entity:
          domain: input_number
    idle_timeout:
      name: Idle Timeout
      description: How long to wait before resetting the control state?
      default: { seconds: 30 }
      selector:
        duration:

mode: single
max_exceeded: silent

triggers:
- trigger: state
  attribute: current_position
  entity_id: !input covers
  for: !input idle_timeout
  id: reset
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    <<: &event_data
      device_id: !input switch
      command_class_name: Central Scene
    property_key: '001'
  id: up_event
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    <<: *event_data
    property_key: '002'
  id: down_event

variables:
  event: '{{ trigger.event.data.value if trigger.id in ["up_event", "down_event"] else None }}'
  paddle_hold: !input paddle_hold
  paddle_taps: !input paddle_taps
  state_variable: !input state_variable
  state: '{{ int(states(state_variable)) }}'
  # 0=nothing 1=opening 2=opening_stopped 3=closing 4=closing_stopped

actions:
- choose:
  - conditions:
    - '{{ trigger.id == "reset" }}'
    sequence:
    - action: input_number.set_value
      data: { value: 0 }
      target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "up_event" and event == paddle_taps }}'
    sequence:
    - choose:
      - conditions:
        - '{{ state in [0, 2, 4] }}'
        sequence: &open_covers
        - action: cover.open_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 1 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 3 }}'
        sequence: &stop_closing
        - action: cover.stop_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 4 }
          target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "up_event" and event == "KeyHeldDown" }}'
    - '{{ paddle_hold }}'
    - '{{ state in [0, 2, 3, 4] }}'
    sequence: *open_covers

  - conditions:
    - '{{ trigger.id == "up_event" and event == "KeyReleased" }}'
    - '{{ paddle_hold }}'
    - '{{ state == 1 }}'
    sequence: &stop_opening
    - action: cover.stop_cover
      target: { entity_id: !input covers }
    - action: input_number.set_value
      data: { value: 2 }
      target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "down_event" and event == paddle_taps }}'
    sequence:
    - choose:
      - conditions:
        - '{{ state in [0, 2, 4] }}'
        sequence: &close_covers
        - action: cover.close_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 3 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 1 }}'
        sequence: *stop_opening

  - conditions:
    - '{{ trigger.id == "down_event" and event == "KeyHeldDown" }}'
    - '{{ paddle_hold }}'
    - '{{ state in [0, 1, 2, 4] }}'
    sequence: *close_covers

  - conditions:
    - '{{ trigger.id == "down_event" and event == "KeyReleased" }}'
    - '{{ paddle_hold }}'
    - '{{ state == 3 }}'
    sequence: *stop_closing
