blueprint:
  name: Reload Blueprints
  description: Automatically reload blueprints on file changes.
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/reload_blueprints.yaml
  input: {}

mode: single

triggers:
- trigger: event
  event_type: folder_watcher
  event_data:
    event_type: closed
- trigger: event
  event_type: folder_watcher
  event_data:
    event_type: moved

conditions:
- condition: or
  conditions:
  - '{{ trigger.event.data.event_type == "closed" and trigger.event.data.file[-5:] == ".yaml" }}'
  - '{{ trigger.event.data.event_type == "moved" and trigger.event.data.dest_file[-5:] == ".yaml" }}'

action:
- choose:
  - conditions:
    - '{{ "blueprints/automation" in trigger.event.data.folder }}'
    sequence:
    - action: automation.reload

  - conditions:
    - '{{ "blueprints/script" in trigger.event.data.folder }}'
    sequence:
    - action: script.reload
