blueprint:
  name: Remote Automation
  description: Execute sets of actions when a remote turns on or off or changes.
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/remote_automation.yaml
  input:
    remote:
      name: Remote
      description: Which remote to use?
      selector:
        entity:
          domain: remote
    on_conditions:
      name: On Conditions
      description: What conditions should be checked before running the on actions?
      default: []
      selector: &conditions-selector
        condition:
    on_actions:
      name: On Actions
      description: What should we do when the remote turns on?
      default: []
      selector: &actions-selector
        action:
    off_conditions:
      name: Off Conditions
      description: What conditions should be checked before running the off actions?
      default: []
      selector: *conditions-selector
    off_actions:
      name: Off Actions
      description: What should we do when the remote turns off?
      default: []
      selector: *actions-selector
    change_conditions:
      name: Change Conditions
      description: What conditions should be checked before running the on change actions?
      default: []
      selector: *conditions-selector
    change_actions:
      name: Change Actions
      description: What should we do when the remote changes?
      default: []
      selector: *actions-selector

mode: single

trigger:
- platform: state
  entity_id: !input remote

action:
- if:
  - '{{ trigger.from_state.state == "off" and trigger.to_state.state == "on" }}'
  - condition: !input on_conditions
  then: !input on_actions
- if:
  - '{{ trigger.from_state.state == "on" and trigger.to_state.state == "off" }}'
  - condition: !input on_conditions
  then: !input on_actions
- if:
  - condition: !input change_conditions
  then: !input change_actions
