blueprint:
  name: Water Leak Alerts
  description: Critical push notifications and Alexa annoucements when a water leak is detected.
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/water_leak_alerts.yaml
  input:
    area:
      name: Area
      description: What is the name of the area for the alert?
      selector:
        text:
    leak_sensors:
      name: Leak Sensors
      description: Which sensors should be monitored?
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    delay:
      name: Repeat Delay
      description: How long to wait before repeating the alert?
      default: { minutes: 2 }
      selector:
        duration:

mode: single
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input leak_sensors
  to: 'on'

variables:
  area: !input area

action:
- repeat:
    while:
    - condition: state
      entity_id: !input leak_sensors
      match: any
      state: 'on'
    sequence:
    - action: notify.notify
      data:
        data: { push: { sound: { name: Default, critical: 1, volume: 1.0 } } }
        message: 'Water leak in {{ area }}!'
        title: Water Leak!
    - action: notify.alexa_media
      data:
        data: { type: announce }
        message: 'Alert! Water leak in {{ area }}!'
        target: media_player.everywhere
        title: WATER LEAK!
    - delay: !input delay
