blueprint:
  name: Zooz ZEN76/77 Lights
  description: Control lights (or fans/switches) with paddle taps on a Zooz ZEN67/77 switch.
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/zooz_zen7677_lights.yaml
  input:
    switch:
      name: Switch
      description: Which switch to use?
      selector:
        device:
          filter:
          - { manufacturer: Zooz, model: ZEN76 }
          - { manufacturer: Zooz, model: ZEN77 }
    paddle_taps:
      name: Paddle Taps
      description: How many taps on a paddle are required?
      default: 'KeyPressed'
      selector:
        select:
          mode: dropdown
          options:
          - label: 'Single'
            value: 'KeyPressed'
          - label: 'Double'
            value: 'KeyPressed2x'
          - label: 'Triple'
            value: 'KeyPressed3x'
          - label: 'Quadruple'
            value: 'KeyPressed4x'
          - label: 'Quintuple'
            value: 'KeyPressed5x'
    double_tap:
      name: Double Tap
      description: Instantly change brightness with paddle double tap?
      default: false
      selector:
        boolean:
    double_tap_up_brightness:
      name: Double Tap Up Brightness
      description: What brightness to use when double tapping the up paddle?
      default: 100
      selector: &brightness-selector
        number:
          max: 100
          min: 0
          unit_of_measurement: '%'
    double_tap_down_brightness:
      name: Double Tap Down Brightness
      description: What brightness to use when double tapping the down paddle?
      default: 30
      selector: *brightness-selector
    paddle_hold:
      name: Paddle Hold
      description: Brighten or dim the lights when holding down a paddle?
      default: false
      selector:
        boolean:
    paddle_hold_step_brightness:
      name: Paddle Hold Step Brightness
      description: How much to increase or decrease brightness per paddle hold step?
      default: 10
      selector: *brightness-selector
    paddle_hold_step_interval:
      name: Paddle Hold Step Interval
      description: How long between paddle hold steps?
      default: 600
      selector:
        number:
          max: 2000
          min: 200
          step: 10
          unit_of_measurement: ms
    subjects:
      name: Lights
      description: Which lights (or fans/switches) to control with the paddles?
      selector:
        entity:
          domain: ['fan', 'light', 'switch']
          multiple: true

mode: restart

triggers:
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    <<: &event_data
      device_id: !input switch
      command_class_name: Central Scene
    property_key: '001'
  id: up_event
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    <<: *event_data
    property_key: '002'
  id: down_event

variables:
  double_tap: !input double_tap
  double_tap_down_brightness: !input double_tap_down_brightness
  double_tap_up_brightness: !input double_tap_up_brightness
  event: '{{ trigger.event.data.value if trigger.id in ["up_event", "down_event"] else None }}'
  paddle_hold: !input paddle_hold
  paddle_hold_step_brightness: !input paddle_hold_step_brightness
  paddle_hold_step_interval: !input paddle_hold_step_interval
  paddle_taps: !input paddle_taps
  subjects: !input subjects
  subjects_list: '{{ subjects is list and subjects or [subjects] }}'
  fans: '{{ subjects_list | select("search", "^fan\.") | list }}'
  lights: '{{ subjects_list | select("search", "^light\.") | list }}'
  switches: '{{ subjects_list | select("search", "^switch\.") | list }}'

actions:
- choose:
  - conditions:
    - '{{ trigger.id == "up_event" and event == paddle_taps }}'
    sequence:
    - action: fan.turn_on
      target: { entity_id: '{{ fans }}' }
    - action: light.turn_on
      target: { entity_id: '{{ lights }}' }
    - action: switch.turn_on
      target: { entity_id: '{{ switches }}' }

  - conditions:
    - '{{ trigger.id == "up_event" and event == "KeyPressed2x" }}'
    - '{{ double_tap }}'
    sequence:
      action: light.turn_on
      target: { entity_id: '{{ lights }}' }
      data: { brightness_pct: '{{ double_tap_up_brightness }}' }

  - conditions:
    - '{{ trigger.id == "up_event" and event == "KeyHeldDown" }}'
    - '{{ paddle_hold }}'
    sequence:
    - repeat:
        sequence:
        - action: light.turn_on
          target: { entity_id: '{{ lights }}' }
          data: { brightness_step_pct: '{{ paddle_hold_step_brightness }}' }
        - delay: { milliseconds: '{{ paddle_hold_step_interval }}' }
        until: '{{ min(expand(lights) | map(attribute="attributes.brightness") | map("int", 0)) >= 255 }}'

  - conditions:
    - '{{ trigger.id == "up_event" and event == "KeyReleased" }}'
    - '{{ paddle_hold }}'
    sequence: []

  - conditions:
    - '{{ trigger.id == "down_event" and event == paddle_taps }}'
    sequence:
    - action: fan.turn_off
      target: { entity_id: '{{ fans }}' }
    - action: light.turn_off
      target: { entity_id: '{{ lights }}' }
    - action: switch.turn_off
      target: { entity_id: '{{ switches }}' }

  - conditions:
    - '{{ trigger.id == "down_event" and event == "KeyPressed2x" }}'
    - '{{ double_tap }}'
    sequence:
      action: light.turn_on
      target: { entity_id: '{{ lights }}' }
      data: { brightness_pct: '{{ double_tap_down_brightness }}' }

  - conditions:
    - '{{ trigger.id == "down_event" and event == "KeyHeldDown" }}'
    - '{{ paddle_hold }}'
    sequence:
    - repeat:
        sequence:
        - action: light.turn_on
          target: { entity_id: '{{ lights }}' }
          data: { brightness_step_pct: '{{ -paddle_hold_step_brightness }}' }
        - delay: { milliseconds: '{{ paddle_hold_step_interval }}' }
        until: '{{ min(expand(lights) | map(attribute="attributes.brightness") | map("int", 0)) <= 0 }}'

  - conditions:
    - '{{ trigger.id == "down_event" and event == "KeyReleased" }}'
    - '{{ paddle_hold }}'
    sequence: []
