blueprint:
  name: Zooz ZEN32 Lights
  description: Binds a key on a Zooz ZEN32 to control lights (or fans/switches)
  domain: automation
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/zooz_zen32_lights.yaml
  input:
    controller:
      name: Controller
      description: Which Zooz ZEN32 controller to use
      selector:
        device:
          filter:
          - { manufacturer: Zooz, model: ZEN32 }
    key:
      name: Key
      default: '005'
      description: Which key on the controller to use
      selector:
        select:
          mode: dropdown
          options:
          - label: '1 (Top)'
            value: '005'
          - label: '2 (Mid Left)'
            value: '001'
          - label: '3 (Mid Right)'
            value: '002'
          - label: '4 (Bottom Left)'
            value: '003'
          - label: '5 (Bottom Right)'
            value: '004'
    led_enable:
      name: Enable LED
      description: Enable changing the LED to reflect the state of the covers
      default: true
      selector:
        boolean:
    subjects:
      name: Lights
      description: Which lights (or fans/switches) to control with the key
      selector:
        entity:
          domain: ['fan', 'light', 'switch']
          multiple: true

mode: single
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input subjects
  to: 'on'
  id: lightOn
- platform: state
  entity_id: !input subjects
  to: 'off'
  id: lightOff
- platform: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input controller
    command_class_name: Central Scene
    property_key: !input key
    value: KeyPressed
  id: keyPressed
- platform: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input controller
    command_class_name: Central Scene
    property_key: !input key
    value: KeyPressed2x
  id: keyPressed2x

variables:
  controller: !input controller
  key: !input key
  key_led_param: '{{ int(key) % 5 + 1 }}'
  led_enable: !input led_enable
  subjects: !input subjects
  fans: '{{ subjects | select("search", "^fan.") | list }}'
  lights: '{{ subjects | select("search", "^light.") | list }}'
  switches: '{{ subjects | select("search", "^switch.") | list }}'

action:
- choose:
  - conditions:
    - condition: trigger
      id: lightOn
    - condition: template
      value_template: '{{ led_enable }}'
    sequence:
    - service: zwave_js.set_config_parameter
      data: { parameter: '{{ key_led_param }}', value: 3 }
      target: { device_id: '{{ controller }}' }

  - conditions:
    - condition: trigger
      id: lightOff
    - condition: template
      value_template: '{{ led_enable }}'
    sequence:
    - service: zwave_js.set_config_parameter
      data: { parameter: '{{ key_led_param }}', value: 2 }
      target: { device_id: '{{ controller }}' }

  - conditions:
    - condition: trigger
      id: keyPressed
    - condition: template
      value_template: '{{ int(trigger.event.data.property_key) == int(key) }}'
    sequence:
    - if:
      - condition: state
        entity_id: !input subjects
        match: any
        state: 'off'
      then:
      - service: fan.turn_on
        target: { entity_id: '{{ fans }}' }
      - service: light.turn_on
        target: { entity_id: '{{ lights }}' }
      - service: switch.turn_on
        target: { entity_id: '{{ switches }}' }
      - if:
        - condition: template
          value_template: '{{ led_enable }}'
        then:
        - service: zwave_js.set_config_parameter
          data: { parameter: '{{ key_led_param }}', value: 3 }
          target: { device_id: '{{ controller }}' }
      else:
      - service: fan.turn_off
        target: { entity_id: '{{ fans }}' }
      - service: light.turn_off
        target: { entity_id: '{{ lights }}' }
      - service: switch.turn_off
        target: { entity_id: '{{ switches }}' }
      - if:
        - condition: template
          value_template: '{{ led_enable }}'
        then:
        - service: zwave_js.set_config_parameter
          data: { parameter: '{{ key_led_param }}', value: 2 }
          target: { device_id: '{{ controller }}' }

  - conditions:
    - condition: trigger
      id: keyPressed2x
    - condition: template
      value_template: '{{ int(trigger.event.data.property_key) == int(key) }}'
    sequence:
    - service: fan.turn_on
      data: { percentage: 100 }
      target: { entity_id: '{{ fans }}' }
    - service: light.turn_on
      data: { brightness_pct: 100 }
      target: { entity_id: '{{ lights }}' }
    - service: switch.turn_on
      target: { entity_id: '{{ switches }}' }
    - if:
      - condition: template
        value_template: '{{ led_enable }}'
      then:
      - service: zwave_js.set_config_parameter
        data: { parameter: '{{ key_led_param }}', value: 3 }
        target: { device_id: '{{ controller }}' }
