blueprint:
  name: Zooz ZEN76/77 Actions
  description: Run custom actions with paddle taps on a Zooz ZEN67/77 switch
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/zooz_zen7677_actions.yaml
  input:
    switch:
      name: Switch
      description: Which switch to use?
      selector:
        device:
          filter:
          - { manufacturer: Zooz, model: ZEN76 800LR }
          - { manufacturer: Zooz, model: ZEN77 800LR }
    paddle_taps:
      name: Paddle Taps
      description: How many taps on a paddle are required?
      default: 'KeyPressed'
      selector:
        select:
          mode: dropdown
          options:
          - label: 'Single'
            value: 'KeyPressed'
          - label: 'Double'
            value: 'KeyPressed2x'
          - label: 'Triple'
            value: 'KeyPressed3x'
          - label: 'Quadruple'
            value: 'KeyPressed4x'
          - label: 'Quintuple'
            value: 'KeyPressed5x'
    up_actions:
      name: Up Actions
      description: What should we do when the up paddle is tapped?
      default: []
      selector: &actions-selector
        action:
    down_actions:
      name: Down Actions
      description: What should we do when the down paddle is tapped?
      default: []
      selector: *actions-selector

mode: single
max_exceeded: silent

trigger_variables:
  paddle_taps: !input paddle_taps

triggers:
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input switch
    command_class_name: Central Scene
    property_key: '001'
    value: '{{ paddle_taps }}'
  id: up_pressed
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input switch
    command_class_name: Central Scene
    property_key: '002'
    value: '{{ paddle_taps }}'
  id: down_pressed

actions:
- choose:
  - conditions:
    - '{{ trigger.id == "up_pressed" }}'
    sequence: !input up_actions

  - conditions:
    - '{{ trigger.id == "down_pressed" }}'
    sequence: !input down_actions
