blueprint:
  name: Zooz ZEN32 Covers
  description: Control covers with a Zooz ZEN32 scene controller.
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/zooz_zen32_covers.yaml
  input:
    controller:
      name: Controller
      description: Which scene controller to use?
      selector:
        device:
          filter:
          - { manufacturer: Zooz, model: ZEN32 }
    key:
      name: Key
      default: '005'
      description: Which button on the controller to use?
      selector:
        select:
          mode: dropdown
          options:
          - label: '1 (Top)'
            value: '005'
          - label: '2 (Mid Left)'
            value: '001'
          - label: '3 (Mid Right)'
            value: '002'
          - label: '4 (Bottom Left)'
            value: '003'
          - label: '5 (Bottom Right)'
            value: '004'
    led_enable:
      name: Enable LED
      description: Use the LED to show the state of the lights?
      default: true
      selector:
        boolean:
    led_invert:
      name: Invert LED
      description: Invert the LED state?
      default: false
      selector:
        boolean:
    state_variable:
      name: State Variable
      description: |
        This automation requires a Number helper to store the current state of the shade.
        Please create one that goes from 0 to 4 and select it here.
        Must only be shared with automations using the same set of shades.
      selector:
        entity:
          domain: input_number
    covers:
      name: Covers
      description: Which covers to control?
      selector:
        entity:
          domain: cover
          multiple: true

mode: single
max_exceeded: silent

triggers:
- trigger: state
  entity_id: !input covers
  attribute: current_position
  to: [0, 100]
  for: { seconds: 30 }
  id: reset
- trigger: state
  entity_id: !input covers
  to: open
  id: cover_opened
- trigger: state
  entity_id: !input covers
  to: closed
  id: cover_closed
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input controller
    command_class_name: Central Scene
    property_key: !input key
    value: KeyPressed
  id: key_pressed
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input controller
    command_class_name: Central Scene
    property_key: !input key
    value: KeyHeldDown
  id: key_held_down
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input controller
    command_class_name: Central Scene
    property_key: !input key
    value: KeyReleased
  id: key_released

variables:
  controller: !input controller
  key: !input key
  led_enable: !input led_enable
  led_invert: !input led_invert
  led_off_value: '{{ led_invert and 3 or 2 }}'
  led_on_value: '{{ led_invert and 2 or 3 }}'
  led_param: '{{ int(key) % 5 + 1 }}'
  state_variable: !input state_variable
  state: '{{ int(states(state_variable)) }}'
  # 0=nothing 1=up 2=up_stopped 3=down 4=down_stopped

actions:
- choose:
  - conditions:
    - '{{ trigger.id == "reset" }}'
    sequence:
    - action: input_number.set_value
      data: { value: 0 }
      target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "cover_opened" }}'
    - '{{ led_enable }}'
    sequence:
    - action: zwave_js.set_config_parameter
      data: { parameter: '{{ led_param }}', value: '{{ led_on_value }}' }
      target: { device_id: '{{ controller }}' }

  - conditions:
    - '{{ trigger.id == "cover_closed" }}'
    - '{{ led_enable }}'
    sequence:
    - action: zwave_js.set_config_parameter
      data: { parameter: '{{ led_param }}', value: '{{ led_off_value }}' }
      target: { device_id: '{{ controller }}' }

  - conditions:
    - '{{ trigger.id == "key_pressed" }}'
    - '{{ int(trigger.event.data.property_key) == int(key) }}'
    sequence:
    - choose:
      - conditions:
        - '{{ state == 0 }}'
        sequence:
        - if:
          - condition: state
            entity_id: !input covers
            state: closed
          then:
          - action: cover.open_cover
            target: { entity_id: !input covers }
          - action: input_number.set_value
            data: { value: 1 }
            target: { entity_id: !input state_variable }
          else:
          - action: cover.close_cover
            target: { entity_id: !input covers }
          - action: input_number.set_value
            data: { value: 3 }
            target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 1 }}'
        sequence:
        - action: cover.stop_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 2 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 2 }}'
        sequence:
        - action: cover.close_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 3 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 3 }}'
        sequence:
        - action: cover.stop_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 4 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 4 }}'
        sequence:
        - action: cover.open_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 1 }
          target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "key_held_down" }}'
    - '{{ int(trigger.event.data.property_key) == int(key) }}'
    sequence:
    - choose:
      - conditions:
        - '{{ state == 0 }}'
        sequence:
        - if:
          - condition: state
            entity_id: !input covers
            state: closed
          then:
          - action: cover.open_cover
            target: { entity_id: !input covers }
          - action: input_number.set_value
            data: { value: 1 }
            target: { entity_id: !input state_variable }
          else:
          - action: cover.close_cover
            target: { entity_id: !input covers }
          - action: input_number.set_value
            data: { value: 3 }
            target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 2 }}'
        sequence:
        - action: cover.close_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 3 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 4 }}'
        sequence:
        - action: cover.open_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 1 }
          target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "key_released" }}'
    - '{{ int(trigger.event.data.property_key) == int(key) }}'
    sequence:
    - choose:
      - conditions:
        - '{{ state == 1 }}'
        sequence:
        - action: cover.stop_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 2 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 3 }}'
        sequence:
        - action: cover.stop_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 4 }
          target: { entity_id: !input state_variable }
