blueprint:
  name: Zooz ZEN76/77 Covers
  description: Control covers with paddle taps on a Zooz ZEN67/77 switch
  domain: automation
  author: Samuel Kadolph
  source_url: https://github.com/samuelkadolph/hass-blueprints/blob/main/automation/samuelkadolph/zooz_zen7677_covers.yaml
  input:
    switch:
      name: Switch
      description: Which switch to use?
      selector:
        device:
          filter:
          - { manufacturer: Zooz, model: ZEN76 }
          - { manufacturer: Zooz, model: ZEN77 }
    paddle_taps:
      name: Paddle Taps
      description: How many taps on a paddle are required?
      default: 'KeyPressed'
      selector:
        select:
          mode: dropdown
          options:
          - label: 'Single'
            value: 'KeyPressed'
          - label: 'Double'
            value: 'KeyPressed2x'
          - label: 'Triple'
            value: 'KeyPressed3x'
          - label: 'Quadruple'
            value: 'KeyPressed4x'
          - label: 'Quintuple'
            value: 'KeyPressed5x'
    paddle_hold:
      name: Paddle Hold
      description: Open and close the covers when holding down a paddle?
      default: true
      selector:
        boolean:
    state_variable:
      name: State Variable
      description: |
        This automation requires a Number helper to store the current state of the shade.
        Please create one that goes from 0 to 4 and select it here.
        Must only be shared with automations using the same set of shades.
      selector:
        entity:
          domain: input_number
    covers:
      name: Covers
      description: Which covers to control with the switch paddles?
      selector:
        entity:
          domain: cover
          multiple: true

mode: single
max_exceeded: silent

trigger_variables:
  paddle_taps: !input paddle_taps

triggers:
- trigger: state
  attribute: current_position
  entity_id: !input covers
  to: [0, 100]
  for: { seconds: 30 }
  id: reset
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input switch
    command_class_name: Central Scene
    property_key: '001'
    value: '{{ paddle_taps }}'
  id: up_pressed
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input switch
    command_class_name: Central Scene
    property_key: '001'
    value: 'KeyHeldDown'
  id: up_held_down
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input switch
    command_class_name: Central Scene
    property_key: '001'
    value: 'KeyReleased'
  id: up_released
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input switch
    command_class_name: Central Scene
    property_key: '002'
    value: '{{ paddle_taps }}'
  id: down_pressed
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input switch
    command_class_name: Central Scene
    property_key: '002'
    value: 'KeyHeldDown'
  id: down_held_down
- trigger: event
  event_type: zwave_js_value_notification
  event_data:
    device_id: !input switch
    command_class_name: Central Scene
    property_key: '002'
    value: 'KeyReleased'
  id: down_released

variables:
  paddle_hold: !input paddle_hold
  state_variable: !input state_variable
  state: '{{ int(states(state_variable)) }}'
  # 0=nothing 1=up 2=up_stopped 3=down 4=down_stopped

action:
- choose:
  - conditions:
    - '{{ trigger.id == "reset" }}'
    sequence:
    - action: input_number.set_value
      data: { value: 0 }
      target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "up_pressed" }}'
    sequence:
    - choose:
      - conditions:
        - '{{ state in [0, 2, 4] }}'
        sequence:
        - action: cover.open_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 1 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 3 }}'
        sequence:
        - action: cover.stop_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 4 }
          target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "up_held_down" }}'
    - '{{ paddle_hold }}'
    - '{{ state in [0, 2, 3, 4] }}'
    sequence:
    - action: cover.open_cover
      target: { entity_id: !input covers }
    - action: input_number.set_value
      data: { value: 1 }
      target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "up_released" }}'
    - '{{ paddle_hold }}'
    - '{{ state == 1 }}'
    sequence:
    - action: cover.stop_cover
      target: { entity_id: !input covers }
    - action: input_number.set_value
      data: { value: 2 }
      target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "down_pressed" }}'
    sequence:
    - choose:
      - conditions:
        - '{{ state in [0, 2, 4] }}'
        sequence:
        - action: cover.close_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 3 }
          target: { entity_id: !input state_variable }
      - conditions:
        - '{{ state == 1 }}'
        sequence:
        - action: cover.stop_cover
          target: { entity_id: !input covers }
        - action: input_number.set_value
          data: { value: 2 }
          target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "down_held_down" }}'
    - '{{ paddle_hold }}'
    - '{{ state in [0, 1, 2, 4] }}'
    sequence:
    - action: cover.close_cover
      target: { entity_id: !input covers }
    - action: input_number.set_value
      data: { value: 3 }
      target: { entity_id: !input state_variable }

  - conditions:
    - '{{ trigger.id == "down_released" }}'
    - '{{ paddle_hold }}'
    - '{{ state == 3 }}'
    sequence:
    - action: cover.stop_cover
      target: { entity_id: !input covers }
    - action: input_number.set_value
      data: { value: 4 }
      target: { entity_id: !input state_variable }
